name: Build CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: Build all extenions
        run: npm run build:all
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            dist
            index.json
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout to repo branch
        uses: actions/checkout@v3
        with:
          ref: repo
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - name: Check diff
        run: git diff --quiet
      - name: Commit generated files
        if: failure()
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "generated"
          git push
