name: Build CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build all extenions
        run: npm run build:all
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout to repo branch
        uses: actions/checkout@v3
        with:
          ref: repo
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Update dist files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist
          git commit -m "generated"
          git push
